### ISSUE TITLE
TLS1.3

### ISSUE THREAD

**Issue by datiscum** [iLya2IK/wchttpserver#3]
I tested the sample server and it worked without any problems. However, the connection in Firefox only used "TLSv1.2" as specified with "Application.ESServer.SSLType:= stTLSv1_2". If I specify it with "Application.ESServer.SSLType:= stAny", TLSv1.3 is automatically used.
Is there a reason why you are specifying "TLSv1.2" ?

I use OpenSSL1.1.1.

Many thanks

**Comment by iLya2IK** [comment]
Thanks for your comment. I just did not test the server with TLS ver 1.3 for operability. But I think that there should be no problems when switching to a new version. Note that in order to fully use TLS 1.3, you need to update the list of Cipher suites: https://wiki.mozilla.org/Security/Server_Side_TLS
Look at OpenSSL.SSLCipherList in server.cfg
